research_company_culture_task:
  description: >
    Analyze the provided company website and the hiring manager's company's domain {company_domain},
    description {company_description}. Focus on understanding the company's culture, values, and mission.
    Identify unique selling points and specific projects or achievements highlighted on the site.
    Compile a report summarizing these insights, specifically how they can be leveraged in a job posting
    to attract the right candidates.
  expected_output: >
    A comprehensive report detailing the company's culture, values, and mission, along with specific selling
    points relevant to the job role. Suggestions on incorporating these insights into the job posting should be included.

research_role_requirements_task:
  description: >
    Based on the hiring manager's needs: {hiring_needs}, identify the key skills, experiences,
    and qualities the ideal candidate should possess for the role. Consider the company's current projects,
    its competitive landscape, and industry trends. Prepare a list of recommended job requirements
    and qualifications that align with the company's needs and values.
    
    SALARY RESEARCH REQUIREMENTS:
    - Research current industry salary standards for the specific role and location
    - For Production Assistant roles in Los Angeles: Research typical range ($44,000-$54,000 annually, $21-26/hour)
    - Consider company size, industry sector, and role level when determining appropriate range
    - Provide justification for the proposed salary range based on market data
  expected_output: >
    A list of recommended skills, experiences, and qualities for the ideal candidate, aligned with
    the company's culture, ongoing projects, and the specific role's requirements. Must include
    researched salary range recommendation with market justification for legal compliance.

draft_job_posting_task:
  description: >
    Draft a job posting for the role described by the hiring manager: {hiring_needs}.
    Use the insights on {company_description} to start with a compelling introduction,
    followed by a detailed role description, responsibilities, and required skills and qualifications.
    Ensure the tone aligns with the company's culture and incorporate any unique benefits or
    opportunities offered by the company. Specific benefits: {specific_benefits}.
    Include a Location section as exactly:
    Location
    Remote - Global Team
    
    COMPLIANCE REQUIREMENTS:
    - MUST include a salary range section that complies with US jurisdictional transparency requirements
    - Research industry standards for the specific role and location to determine appropriate salary range
    - If exact salary range cannot be determined, mark as "Salary Range: TBD - Will be determined based on experience and qualifications" with legal justification
    - Ensure the salary range reflects current market conditions and is competitive for the role level
  expected_output: >
    A detailed, engaging job posting that includes an introduction, role description, responsibilities,
    requirements, salary range (MANDATORY for compliance), and unique company benefits. The tone should resonate with the company's culture
    and values, aimed at attracting the right candidates. The salary range must be included to meet legal transparency requirements. 


review_and_edit_job_posting_task:
  description: >
    Review the draft job posting for the role {hiring_needs}. Check for clarity, engagement, grammatical accuracy,
    and alignment with the company's culture and values. Edit and refine the content, ensuring it speaks directly
    to the desired candidates and accurately reflects the role's unique benefits and opportunities. Provide
    feedback for any necessary revisions.
    
    COMPLIANCE VALIDATION:
    - MANDATORY: Verify that the job posting includes a salary range section for legal compliance
    - Ensure salary range is realistic and competitive based on industry standards
    - If salary range is marked as TBD, ensure proper legal justification is provided
    - Validate that all US jurisdictional transparency requirements are met
  expected_output: >
    A polished, error-free job posting that is clear, engaging, and perfectly aligned with the company's culture and values.
    Must include a compliant salary range section. Feedback on potential improvements and final approval for publishing. 
    Formatted in markdown with confirmed legal compliance for salary transparency requirements.

industry_analysis_task:
  description: >
    Conduct an in-depth analysis of the industry related to the company's domain {company_domain}.
    Investigate current trends, challenges, and opportunities within the industry, utilizing market reports,
    recent developments, and expert opinions. Assess how these factors could impact the role being hired
    for and the overall attractiveness of the position to potential candidates.
    Consider how the company's position within this industry and its response to these trends could be leveraged to attract top talent.
    Include in your report how the role contributes to addressing industry challenges or seizing opportunities.
  expected_output: >
    A detailed analysis report that identifies major industry trends, challenges, and opportunities relevant
    to the company's domain and the specific job role. This report should provide strategic insights on positioning
    the job role and the company as an attractive choice for potential candidates.
