research_task:
  description: >
    Conduct a thorough research about the customer and competitors in the context
    of {customer_domain}.
    Make sure you find any interesting and relevant information given the
    current year is 2024.
    We are working with them on the following project: {project_description}.
  expected_output: >
    A complete report on the customer and their customers and competitors,
    including their demographics, preferences, market positioning and audience engagement.

project_understanding_task:
  description: >
    Understand the project details and the target audience for
    {project_description}.
    Review any provided materials and gather additional information as needed.
  expected_output: >
    A detailed summary of the project and a profile of the target audience.

marketing_strategy_task:
  description: >
    Formulate a comprehensive marketing strategy for the project
    {project_description} of the customer {customer_domain}.
    Use the insights from the research task and the project understanding
    task to create a high-quality strategy.
  expected_output: >
    A detailed marketing strategy document that outlines the goals, target
    audience, key messages, and proposed tactics, make sure to have name, tatics, channels and KPIs

campaign_idea_task:
  description: >
    Develop creative marketing campaign ideas for {project_description}.
    Ensure the ideas are innovative, engaging, and aligned with the overall marketing strategy.
  expected_output: >
    A list of 5 campaign ideas, each with a brief description and expected impact.

copy_creation_task:
  description: >
    Create marketing copies based on the approved campaign ideas for {project_description}.
    Ensure the copies are compelling, clear, and tailored to the target audience.
  expected_output: >
    Marketing copies for each campaign idea.

weather_inquiry_task:
  description: >
    Respond to user weather inquiries with comprehensive, contextually rich information.
    When a user asks about weather conditions (e.g., "What's the weather in Paris in Fahrenheit and then add 10 to the temperature?"),
    you must:
    
    1. Retrieve the current weather data using the get_current_weather tool
    2. Perform any requested calculations accurately
    3. IMPORTANT: Provide contextual information along with the numerical output when responding to weather inquiries
    4. Explain what the temperature and conditions mean in practical terms
    5. Include relevant details such as how the weather might feel, what it means for daily activities, or any notable aspects of the conditions
    
    Your response should NOT be just a number. Instead, provide a user-centric explanation that includes:
    - The numerical answer to their specific question
    - Context about the actual weather conditions
    - Practical implications or helpful commentary about what these conditions mean
    
    Example response format:
    Instead of: "The temperature is 75°F"
    Provide: "The current temperature in Paris is 65°F, and with your requested addition of 10 degrees, that gives us 75°F. This is quite pleasant weather - comfortably warm but not hot, ideal for outdoor activities. The conditions are partly cloudy, so you'll enjoy some sunshine with occasional cloud cover."
    
    Always prioritize clarity, helpfulness, and user understanding over brevity.
  expected_output: >
    A comprehensive weather response that includes:
    1. The accurate numerical answer to the user's query (including any calculations)
    2. Contextual information about the current weather conditions
    3. Practical insights about what these conditions mean for the user
    4. User-friendly language that enhances understanding rather than just stating facts
