research_task:
  description: >
    Conduct a thorough research about the customer and competitors in the context
    of {customer_domain}.
    Make sure you find any interesting and relevant information given the
    current year is 2024.
    We are working with them on the following project: {project_description}.
  expected_output: >
    A complete report on the customer and their customers and competitors,
    including their demographics, preferences, market positioning and audience engagement.

project_understanding_task:
  description: >
    Understand the project details and the target audience for
    {project_description}.
    Review any provided materials and gather additional information as needed.
  expected_output: >
    A detailed summary of the project and a profile of the target audience.

marketing_strategy_task:
  description: >
    Formulate a comprehensive marketing strategy for the project
    {project_description} of the customer {customer_domain}.
    Use the insights from the research task and the project understanding
    task to create a high-quality strategy.
  expected_output: >
    A detailed marketing strategy document that outlines the goals, target
    audience, key messages, and proposed tactics, make sure to have name, tatics, channels and KPIs

campaign_idea_task:
  description: >
    Develop creative marketing campaign ideas for {project_description}.
    Ensure the ideas are innovative, engaging, and aligned with the overall marketing strategy.
  expected_output: >
    A list of 5 campaign ideas, each with a brief description and expected impact.

copy_creation_task:
  description: >
    Create marketing copies based on the approved campaign ideas for {project_description}.
    Ensure the copies are compelling, clear, and tailored to the target audience.
  expected_output: >
    Marketing copies for each campaign idea.

weather_inquiry:
  description: >
    What's the weather in {location} in {temperature_unit}? 
    
    IMPORTANT: Please provide the temperature along with relevant context and explanations.
    Include details such as:
    - Whether this temperature is typical for the season
    - How it compares to recent weather patterns
    - What this temperature means in practical terms (e.g., "pleasantly warm", "quite cold", "uncomfortably hot")
    - Any recommendations for appropriate clothing or activities
    - Additional relevant weather conditions (humidity, wind, precipitation) if significant
    
    Your response should be informative and help the user understand the weather situation,
    not just provide a raw number.
  expected_output: >
    A comprehensive weather report that includes the temperature in the requested unit
    along with contextual information about what that temperature means, how it compares
    to normal conditions, and practical advice for the user. The response should be
    conversational and helpful, making the weather data meaningful and actionable.
